; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = AudioPlayer

[env:black_f407zg]
platform = ststm32
board = black_f407zg
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_port = COM9
monitor_speed = 115200


board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.disable_embedded_libs = yes

build_unflags =
    -mfloat-abi=soft

build_flags =
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -I AudioPlayer/Core/Inc
    -I AudioPlayer/Middlewares/Third_Party/FreeRTOS/Source/include
    -I AudioPlayer/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F

build_src_filter =
    -<*>
    +<Core/Src/main.c>
    +<Core/Src/freertos.c>
    +<Core/Src/stm32f4xx_hal_msp.c>
    +<Core/Src/stm32f4xx_hal_timebase_tim.c>
    +<Core/Src/stm32f4xx_it.c>
    +<Core/Src/spark_lcd.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/*.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c>
    +<Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c>
        +<Core/Src/spark_audio.c>